### ISSUE TITLE
Flux support

### ISSUE THREAD

**Issue by AdamBrodzinski** [kadirahq/meteor-reaktor#3]
It would be nice if we could have an optional prop to hookup to a flux action that is called whenever the FlowRouter data changes. The param could contain a payload of the current state of the router so that a store can update it's state and any views concerned can subscribe to it.

I realize that we can use the props from the parent page (which is super nice!) but my experience with NavigatorIOS and it's similar layout is that it can be a pain to thread props down through many children. It can be easier for a ChildContainer to subscribe directly to the RouterStore.

Also triggering the action on change can log a changed action in the dispatcher which can be used for 'time travel' or debugging.

Currently with vanilla FR i'm calling it in every action.

Something like below would be ideal. Thoughts?

```
Reaktor.init(
    <Router onChange={ RouterActions.changed }>
      <Route .... />
      <Route .... />
    </Router>
  );
```

You could also use a `changedAction` prop...not sure what's more semantic.

**Comment by arunoda** [comment]
So, this is very similar to triggers right? You want to update RouterActions for every route change. So, then we can simply use FR triggers. 
Isn't that will be a problem?

``` js
FlowRouter.triggers.enter(RouterActions.changed)
```

**Comment by AdamBrodzinski** [comment]
I think that would work well actually! Thanks.

**Comment by arunoda** [comment]
Great. Keep me posted.

**Comment by Beelal** [comment]
Example I have seen shows routing and rendering happening in the same code.

Is it possible to decouple Router and ReactLayout? I would like to call out render in the store as suggested in meteorflux/dispatcher (https://github.com/meteorflux/dispatcher) package:

``` js
FlowRouter.route("/", {
  action: function() {
    Dispatcher.dispatch({ actionType: "GOTO_HOME" });
  }
});

// YourLayoutStore.js
Dispatcher.register(function(payload){
  switch(payload.actionType){
    case "GOTO_HOME":
      FlowLayout.render('MainLayout', { main: 'HomeView' });
      break;
    case "GOTO_BLOG_HOME":
    case "GOTO_BLOG_PAGE":
      FlowLayout.render('MainLayout', { main: 'BlogView' });
      break;
  }
});
```

**Comment by arunoda** [comment]
This is totally possible. You can use `ReactLayout` instead of `FlowLayout`

**Comment by Beelal** [comment]
Getting an error when using universe:modules package and importing router file:

W20150806-17:24:11.940(-7)? (STDERR) Potentially unhandled rejection [2] TypeError: Cannot read property 'prototype' of undefined
W20150806-17:24:11.940(-7)? (STDERR)     at packages/kadira:reaktor/lib/both.jsx:30:15
W20150806-17:24:11.941(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150806-17:24:11.941(-7)? (STDERR)     at [object Object].React.createClass.componentWillMount (packages/kadira:reaktor/lib/both.jsx:29:7)
W20150806-17:24:11.941(-7)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/react-runtime-dev/react.browserify.js:6804:14)
W20150806-17:24:11.941(-7)? (STDERR)     at [object Object].wrapper [as mountComponent](packages/react-runtime-dev/react.browserify.js:13941:21)
W20150806-17:24:11.941(-7)? (STDERR)     at Object.ReactReconciler.mountComponent (packages/react-runtime-dev/react.browserify.js:14758:35)
W20150806-17:24:11.941(-7)? (STDERR)     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (packages/react-runtime-dev/react.browserify.js:13411:44)
W20150806-17:24:11.941(-7)? (STDERR)     at ReactDOMComponent.Mixin._createContentMarkup (packages/react-runtime-dev/react.browserify.js:7956:32)
W20150806-17:24:11.941(-7)? (STDERR)     at ReactDOMComponent.Mixin.mountComponent (packages/react-runtime-dev/react.browserify.js:7866:12)
W20150806-17:24:11.941(-7)? (STDERR)     at Object.ReactReconciler.mountComponent (packages/react-runtime-dev/react.browserify.js:14758:35)
W20150806-17:24:11.941(-7)? (STDERR)    Error loading meteor://router

router.import.jsx:
import Layout from 'components/layout';
import {BlogList, BlogPost} from 'components/blog'

Reaktor.init(
    <Router>
        <Route path="/" layout={Layout} content={BlogList} />
        <Route path="/blog/:postId" layout={Layout} content={BlogPost} />
    </Router>
);

layout.import.jsx:
Layout = React.createClass({
  render() {
    return (
      <div>
        <h1>My Blog </h1>
        {this.props.content}
      </div>
    );
  }
});

main.js:
'use strict';

// Run the code, similar to `require` in AMD.
// You shouldn't provide the .import.jsx suffix.
System.import('router');

blog.import.jsx:
BlogList = React.createClass({
  render() {
    return (
      <div>
        This is the blog list:
        <ul>
          <li><a href="/blog/hello-post">Hello Post</a></li>
        </ul>
      </div>
    );
  }
});

BlogPost = React.createClass({
  render() {
    return (
      <div>
        <p><a href="/">Back</a></p>
        This is the blog post
      </div>
    );
  }
});

**Comment by Beelal** [comment]
You can get app code from https://www.dropbox.com/s/kpe06wbg5zu8ipm/demo_modules_reaktor.zip?dl=0

I have replaced flow router with reaktor from this working example https://github.com/vazco/demo_modules
